---
name: Functional Tests (Local)

on: # yamllint disable-line rule:truthy
  pull_request: {}

defaults:
  run:
    shell: sh

jobs:
  run-script:
    name: Run script
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup Whitespace
        uses: ./
      - name: Validate script
        run: |
          [ "$(wspace helloworld.ws)" = "Hello, World!" ] || exit 1;
